name: qube2-mod
channels:
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex
  - ca-certificates
  - certifi
  - libedit>=3.1.20181209
  - libffi>=3.2.1
  - libgcc-ng>=9.1.0
  - libstdcxx-ng>=9.1.0
  - ncurses>=6.1
  - openssl>=1.1.1d
  - pip
  - python=3.7.6
  - readline>=7.0
  - setuptools
  - sqlite>=3.29.0
  - tk>=8.6.8
  - wheel
  - xz>=5.2.4
  - zlib>=1.2.11
  - pytorch
  - pip:
    - asn1crypto==0.24.0
    - attrs==19.1.0
    - autobahn==19.9.3
    - backcall==0.1.0
    - bleach==3.1.0
    - cffi==1.12.3
    - cloudpickle==1.2.2
    - cryptography==2.7
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - future==0.17.1
    - gym==0.14.0
    - ipykernel==5.1.2
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jinja2==2.10.1
    - jsonschema==3.0.2
    - jupyter==1.0.0
    - jupyter-client==5.3.3
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - notebook==6.0.1
    - numpy==1.17.2
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pycparser==2.19
    - pyglet==1.3.2
    - pygments==2.4.2
    - pyrsistent==0.15.4
    - python-dateutil==2.8.0
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - scipy==1.4.0
    - send2trash==1.5.0
    - six==1.12.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tornado==6.0.3
    - traitlets==4.3.2
    - txaio==18.8.1
    - vpnotebook==0.1.3
    - vpython==7.5.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - ipm_furuta>=0.0.4
