name: qube2-stripped
channels:
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex
  - ca-certificates
  - certifi
  - libedit>=3.1.20181209
  - libffi>=3.2.1
  - libgcc-ng>=9.1.0
  - libstdcxx-ng>=9.1.0
  - ncurses>=6.1
  - openssl>=1.1.1d
  - pip
  - python=3.7.6
  - readline>=7.0
  - setuptools
  - sqlite>=3.29.0
  - tk>=8.6.8
  - wheel
  - xz>=5.2.4
  - zlib>=1.2.11
  - pytorch
  - jupyterlab-vpython=3.1.4
  - numpy=1.21.6
  - ipywidgets=8.0.1
  - gym=0.21.0
  - asn1crypto=1.5.1
  - autobahn=22.7.1
  - future=0.18.2
  - pyglet=1.5.16
  - qtconsole=5.3.1
  - testpath=0.6.0
  - scipy=1.7.3
  - seaborn=0.11.2
  - pandas=1.2.3
  - matplotlib-base=3.5.3
  - pip:
    - ipm_furuta>=0.0.4
    - -e ./submodules/quanser-openai-driver
